### ISSUE TITLE
`Timed out getting real device path for /dev/sdf`

### ISSUE THREAD

**Issue by cunnie** [cloudfoundry/bosh-agent#192] opened 2018-09-19 16:14 UTC
When:

- on **AWS**
- using a new instance type (in this case, **t3** (_not_ t2)) (I suspect this plays out for all [ENA-capable](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html#supported_instances) instance types, i.e. C5, C5d, F1, G3, H1, I3, m4.16xlarge, M5, M5d, P2, P3, R4, R5, R5d, T3, X1, X1e, and z1d
- with **Xenial** stemcell
- with a **persistent disk**

The deploy fails with `Timed out getting real device path for /dev/sdf`:

```
Task 7 | 15:42:36 | Updating instance dummy-ubuntu: dummy-ubuntu/1b928c90-f4ed-4d46-9471-d5d67ee0b06e (0) (00:02:20)
                   L Error: Action Failed get_task: Task 7a8c09dc-e5aa-4a51-5b90-8205281aaaa0 result: Mounting persistent disk: Getting real device path: Resolving mapped device path: Timed out getting real device path for /dev/sdf
```

I suspect the problem may be that the agent expects the persistent disk's device file's path to be `/dev/sdf`, but I think it's not — I think the device path is something along the lines of `/dev/nvme2n1`. I manually attached a 5GB volume and ran `fdisk -l` and `df -h` to determine the device path of the additional volume (which I assume would be the same path as a persistent disk):

```
dummy-ubuntu/1b928c90-f4ed-4d46-9471-d5d67ee0b06e:~# fdisk -l
Disk /dev/nvme0n1: 5 GiB, 5368709120 bytes, 10485760 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 8FFD5CAA-AE12-4C94-AA2F-F0B0B458B0A9

Device           Start      End Sectors  Size Type
/dev/nvme0n1p1    2048  1961983 1959936  957M Linux filesystem
/dev/nvme0n1p2 1961984 10483711 8521728  4.1G Linux filesystem


Disk /dev/nvme1n1: 3 GiB, 3221225472 bytes, 6291456 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00098b62

Device         Boot Start     End Sectors Size Id Type
/dev/nvme1n1p1         63 6291422 6291360   3G 83 Linux


Disk /dev/nvme2n1: 5 GiB, 5368709120 bytes, 10485760 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
dummy-ubuntu/1b928c90-f4ed-4d46-9471-d5d67ee0b06e:~# ls -l /dev/sdf
ls: cannot access '/dev/sdf': No such file or directory
dummy-ubuntu/1b928c90-f4ed-4d46-9471-d5d67ee0b06e:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            453M     0  453M   0% /dev
tmpfs            96M  9.6M   87M  11% /run
/dev/nvme1n1p1  2.9G  1.5G  1.4G  52% /
tmpfs           479M     0  479M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           479M     0  479M   0% /sys/fs/cgroup
/dev/nvme0n1p2  3.9G   11M  3.7G   1% /var/vcap/data
tmpfs           1.0M     0  1.0M   0% /var/vcap/data/sys/run
```

- Deployment manifest (without persistent disk): <https://github.com/cunnie/deployments/blob/ef45aa6a836245efb4614eedc76b130bec5a0253/dummy.yml>
- Cloud Config: <https://github.com/cunnie/deployments/blob/ef45aa6a836245efb4614eedc76b130bec5a0253/cloud-config-aws.yml>
- Stemcell version: Xenial 97.16

**Comment by pivotal-mp** [comment] 2018-09-24 19:11
Hi @cunnie,

Just for more context, what version of the [bosh-aws-cpi](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release) are you using?

This was a feature that was added as part of [v72](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/releases/tag/v72) to support disks on `c5`/`m5` instance classes. If you are not using the most recent version of the AWS cpi, could you retry the steps above with that version?

Best,

@pivotal-mp && @jfmyers9, CF BOSH

**Comment by cunnie** [comment] 2018-09-25 10:53
Hi @pivotal-mp && @jfmyers9 ,

I'm using v72; I've been using it since [August 15th](https://github.com/cunnie/deployments/blame/84649fc2691a678fb6f8171111449fe206a664c4/bosh-aws.yml#L1568-L1570).

—Brian

**Comment by pivotal-mp** [comment] 2018-09-26 18:48
Hi @cunnie,

That version seems like it should be good. Can you give us the exact stemcell version and director version you are using?

Thanks!

Best,
@pivotal-mp && @luan

**Comment by dpb587-pivotal** [comment] 2018-09-26 21:44
issue description...

> Xenial 97.16

prior August 15th link...

> version: 268.0.1

@cunnie... still so generous with your environment setup :)

**Comment by cunnie** [comment] 2018-09-27 21:31
Hi @luan @pivotal-mp ,

Director version is [268.0.1](https://github.com/cunnie/deployments/blame/84649fc2691a678fb6f8171111449fe206a664c4/bosh-aws.yml#L1562)

Stemcell used in the deployment is **97.16**:
```
bosh -e aws stemcells
Using environment 'bosh-aws.nono.io' as user 'admin' (openid, bosh.admin)

Name                                     Version  OS             CPI  CID
bosh-aws-xen-hvm-ubuntu-xenial-go_agent  97.16*   ubuntu-xenial  -    ami-02cd4206b92f14d86 light

(*) Currently deployed
```

**Comment by cunnie** [comment] 2018-09-27 21:34
If it would help if I gave you access to my directors, let me know & I'll redeploy my director with an account for you.

**Comment by luan** [comment] 2019-03-19 23:41
This is a duplicate of https://github.com/cloudfoundry/bosh/issues/2128 which has been fixed on the [AWS CPI v74](https://github.com/cloudfoundry/bosh-aws-cpi-release/releases/tag/v74)

**Closed by luan** 2019-03-19 23:41 UTC
Labels: unscheduled
