### ISSUE TITLE
windows agent cpu spikes when the director stops

### ISSUE THREAD

**Issue by flavorjones** [cloudfoundry/bosh-agent#137] opened 2017-08-11 01:15 UTC
Howdy,

Given I have bosh-deployed concourse
And that deployment includes a windows 2012R2 VM
And that windows VM is running the `bosh-google-kvm-windows2012R2-go_agent` v1200.0 stemcell
And I stop the director VM
Then I see the windows agent spike to 100% CPU

Here's a chart from GCP/Stackdriver:

![screenshot from 2017-08-10 21-07-49](https://user-images.githubusercontent.com/8207/29198315-cea37884-7e10-11e7-98d0-678c6634c20a.png)

I'll try to reproduce later and provide more detailed logs from the agent.

**Comment by flavorjones** [comment] 2017-08-11 06:13
It might also be worth noting here that the windows VM is consistently at ~25% CPU utilization, even when nothing is going on. Not clear to me whether this is due to the concourse worker job or the bosh agent.

**Comment by crawsible** [comment] 2017-08-11 07:17
@flavorjones Hrm, very interesting and definitely unexpected (cc: @davidjahn). Thanks for reporting! I've scheduled a bug investigation [in our backlog here](https://www.pivotaltracker.com/story/show/150161953).

FWIW, naively killing the bosh director on my cf deployment using a 1200.1 RC wasn't enough to reproduce this issue for me, which is pretty surprising -- I can't imagine any running process aside from the agent would be affected by the director's accessibility. I think I know the answer, but just to be sure, are you aware of the agent performing any work at the time the director stopped?

**Comment by davidjahn** [comment] 2017-08-11 14:14
Ohhh this is interesting... not sure if the problem is agent induced alone or is some interaction with concourse... we will see if we can reproduce it on GCP.

**Comment by charlievieth** [comment] 2017-08-11 16:45
One thing to note.  When the director dies, the agent will error out and stop, but it's job (the services it creates) will keep running.

**Comment by charlievieth** [comment] 2017-08-11 16:47
Is that red line the agent's CPU usage, and if not do we know which process it correlates to?

**Comment by mhoran** [comment] 2017-08-11 18:32
In investigating this bug, we discovered a completely unrelated bug where the agent will not restart after termination. Thanks!

We're still trying to reproduce the behavior you're seeing. In the stemcell you're using (where the aforementioned unrelated bug is not present), the agent does try to restart when the director connection is lost. We don't see our VMs using 100% CPU, though. Could you tell us a bit more about the instance types in this deployment?

Also, logs from `/var/vcap/bosh/log` would be super helpful.

**Comment by flavorjones** [comment] 2017-08-11 19:45
OK, just landed and will try to reproduce and get y'all some logs and maybe some screenshots from Task Manager.

**Comment by mhoran** [comment] 2017-08-11 19:46
OK, so we do see that, with the default of restarting the agent every 5 seconds on failure, about 25% CPU usage. This is a bit excessive, so we're going to go with an exponential backoff for restarting the agent. We'll back off up to 5 minutes, and then try to start the agent every 5 minutes thereafter. Note that the Linux agent is also [chatty](https://github.com/cloudfoundry/bosh-agent/issues/118) on startup when NATS is unreachable, but probably doesn't have such an expensive bootstrap process.

It's worth noting that with a backoff of 5 minutes, when you bring your director back online and the resurrector is enabled, the resurrector may recreate the VM before the agent has a chance to restart itself.

**Comment by charlievieth** [comment] 2017-08-11 20:19
What about capping the wait at 2.5 minutes that would give you a better chance of reconnecting with the director and is still 30 times longer than 5 seconds?

Sent from my iPhone

On Aug 11, 2017, at 3:46 PM, Matthew Horan <notifications@github.com> wrote:

OK, so we do see that, with the default of restarting the agent every 5 seconds on failure, about 25% CPU usage. This is a bit excessive, so we're going to go with an exponential backoff for restarting the agent. We'll back off up to 5 minutes, and then try to start the agent every 5 minutes thereafter. Note that the Linux agent is also chatty on startup when NATS is unreachable, but probably doesn't have such an expensive bootstrap process.

It's worth noting that with a backoff of 5 minutes, when you bring your director back online and the resurrector is enabled, the resurrector may recreate the VM before the agent has a chance to restart itself.

**Comment by mhoran** [comment] 2017-08-11 20:29
(Hopefully) Fixed in https://github.com/cloudfoundry/bosh-agent/commit/dc9a5b4aea937c56af0e6d8e63e13eb346dcba72.

**Comment by flavorjones** [comment] 2017-08-12 21:21
Looks good. I updated `service_wrapper.xml` with the changes from dc9a5b4 and went through the stop/uninstall/install/start cycle. Here's what CPU util looked like while the director was stopped:

![screenshot from 2017-08-12 17-13-48](https://user-images.githubusercontent.com/8207/29244294-94ab3f68-7f82-11e7-89e5-09b2986a2049.png)

Thanks all!

**Comment by crawsible** [comment] 2017-08-14 05:55
@flavorjones Great to hear! We'll ping back here and close this issue once this agent change makes its way into a 2012R2 stemcell release.

**Comment by cppforlife** [comment] 2017-10-17 20:52
@crawsible did this make it through?

**Comment by crawsible** [comment] 2017-10-18 15:08
@cppforlife Yes it did, thanks for the reminder.

**Closed by crawsible** 2017-10-18 15:08 UTC

**Comment by flavorjones** [comment] 2017-10-18 15:20
For the record, I believe this was patched in 1200.3 (though it may have been 1200.2).
