### ISSUE TITLE
Please remove agent.cert

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-agent#207] opened 2019-01-24 06:03 UTC
/var/vcap/bosh/agent.cert is expired from 2016 and seems it's not used in the code. Would you please remove it in the new stemcell? Thanks.

**Comment by beyhan** [comment] 2019-01-24 07:42
Duplicate of https://github.com/cloudfoundry/bosh-agent/issues/197

**Comment by gu-bin** [comment] 2019-01-24 08:01
But the commit 5e0b8e4e8ac439e4b66b47cc0bab924d3470fd9a which contains the fix is not in the latest `ubuntu-xenial/v170.x`. Would you please put the commit in the new stemcell? Thanks.

**Comment by dpb587-pivotal** [comment] 2019-01-26 00:53
@gu-bin this will be available in the next major stemcell line. Because it is an unneded and unsupported file with minimal risk, we're not planning on backporting the removal to older versions. Let us know if you run into this issue in future versions, or if you have a new concern about the files.

**Closed by dpb587-pivotal** 2019-01-26 00:53 UTC
Labels: unscheduled
