### ISSUE TITLE
Agent could be blocked by blobstore access issues

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh-agent#280] opened 2022-04-26 12:41 UTC
The retry logic for blobstore operations introduced with #258 can block the agent to execute other tasks. This situation can occur when a blobstore operation is triggered from a synchronous task like [sync_dns_with_signed_url](https://github.com/cloudfoundry/bosh-agent/blob/7d83092924307dbc475f26c9b00533bcc3f4c6d5/agent/action/sync_dns_with_signed_url.go#L51) and there are blobstore access issues. In this case agents will try for 15s to access the blobstore and won't be able to start other tasks or respond to task status requests.  This can lead to failed deployments or unresponsive agents shown by the `bosh vms` command. We need to rethink how we can implement the retry logic without blocking the agent by this. Some ideas:

- reduce the wait limit
- retry only from async tasks
- retry only on specific errors like network issues

**Comment by friegger** [comment] 2022-08-10 08:32
Still relevant.

**Comment by rkoster** [comment] 2022-12-15 16:19
@mvach Do you have any context on this?

**Comment by mvach** [comment] 2022-12-22 12:14
Hi @rkoster,
so this issue is still existing and could potentially occur. Team internally we will run a POC to get some insights how to finally fix the issue. Max could offer timelines ;-)

**Comment by mvach** [comment] 2023-02-28 13:09
We cannot reproduce this issue anymore and therefore should close it.

**Comment by rkoster** [comment] 2023-02-28 14:46
@mvach thanks for getting back on this.

**Closed by rkoster** 2023-02-28 14:46 UTC
