### ISSUE TITLE
bosh-agent reporting erroneous disk data on bionic

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloudfoundry/bosh-agent#245] opened 2021-09-01 19:02 UTC
BOSH Director: `271.9.0`
CPI: `AWS/88`
Stemcell: Bionic `1.22`

We moved various deployments off stemcell Xenial `621.125` to Bionic `1.22` and our Prometheus system started to alert on persistent disk usage warnings on various VMs which do not have any persistent disk assigned.  Our alert threshold was set to 75% and most alerts came in between 75.1 and 75.9 after moving the VMs to Bionic.

Looking at the VMs in question I found the following under `/var/vcap/bosh`

`spec.json`
```
  "persistent_disk": 0,
```

`settings.json`
```
    "persistent_disk_fs": "",
    "persistent_disk_mount_options": null,
    "persistent_disk_partitioner": ""
```
`/var/vcap/bosh/log/current`
```
2021-09-01_13:41:22.72666 {"deployment":"cf-production","job":"nats","index":2,"job_state":"running","vitals":{"cpu":{"sys":"0.7","user":"1.7","wait":"0.1"},"disk":{"ephemeral":{"inode_percent":"6","percent":"19"},"persistent":{"inode_percent":"36","percent":"76"},"system":{"inode_percent":"36","percent":"76"}},"load":["0.00","0.06","0.07"],"mem":{"kb":"2426640","percent":"30"},"swap":{"kb":"0","percent":"0"},"uptime":{"secs":87633}},"node_id":"XXXXXXXX"}
```

Since we changed stemcell these where fresh VMs but a `bosh recreate` did not resolve the issue.  We tried to add additional ephemeral disk as well, no change in behavior.  The only way to make the stat drop was to add a persistent disk to the VMs in question.

This appears to have happened before with the `bosh-agent` but these issues suggested a possible code fix and/or nothing done and the issues auto closed for being stale:

https://github.com/cloudfoundry/bosh/issues/2204

https://github.com/cloudfoundry/bosh-agent/issues/36

I'm wondering if a change in the Bionic stemcell to mounts is causing the agent to report erroneous data.  A `df - h` does show the root partition of the stemcell being ~75% in use.  We have not moved forward to the latest Bionic stemcell `1.25` yet as we pinned `1.22` for now until we migrate our whole environment over to Bionic.  I do see from the Bionic release notes that the `bosh-agent` between `1.22` and `1.25` has not changed and is `2.346.0` for both stemcells: 

https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases/tag/ubuntu-bionic%2Fv1.25

https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases/tag/ubuntu-bionic%2Fv1.22

Thanks

**Comment by bgandon** [comment] 2021-09-07 13:04
As an analysis, the root cause seems located here:
https://github.com/cloudfoundry/bosh-agent/blob/main/platform/vitals/service.go#L113-L119
where there is no check that `path` is actually a mount point whereas it is assumed to be a `mountedPath` later here:
https://github.com/cloudfoundry/bosh-agent/blob/main/sigar/sigar_stats_collector.go#L98
without this assumption having been verified anywhere before.

When the directory does not exist, the error is generated by the call to `syscall.Statfs()` there:
https://github.com/cloudfoundry/bosh-agent/blob/main/vendor/github.com/cloudfoundry/gosigar/sigar_unix.go#L9-L12
and then is carried over up the call stack.

**Comment by ChrisMcGowan** [comment] 2021-09-15 15:09
Hi - has there been any movement on this issue?  I see the PR from @bgandon submitted a week ago but it appears that PR has no movement either.  Please advise.

**Comment by bgandon** [comment] 2021-09-17 08:36
That's right. Being part of the BOSH EU team I'm now trying to get the PR reviewed and merged by the US team.
This one is not top of the list, because we have few priorities before, but it's in.

**Closed** 2021-09-29 17:58 UTC
Labels: unscheduled
